package protobuf

import (
	"github.com/golang/protobuf/proto"
)

type CMsgClientChangeStatus struct {
	PersonaState        *uint32 `protobuf:"varint,1,opt,name=persona_state" json:"persona_state,omitempty"`
	PlayerName          *string `protobuf:"bytes,2,opt,name=player_name" json:"player_name,omitempty"`
	IsAutoGeneratedName *bool   `protobuf:"varint,3,opt,name=is_auto_generated_name" json:"is_auto_generated_name,omitempty"`
	HighPriority        *bool   `protobuf:"varint,4,opt,name=high_priority" json:"high_priority,omitempty"`
	PersonaSetByUser    *bool   `protobuf:"varint,5,opt,name=persona_set_by_user" json:"persona_set_by_user,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CMsgClientChangeStatus) Reset()         { *m = CMsgClientChangeStatus{} }
func (m *CMsgClientChangeStatus) String() string { return proto.CompactTextString(m) }
func (*CMsgClientChangeStatus) ProtoMessage()    {}

func (m *CMsgClientChangeStatus) GetPersonaState() uint32 {
	if m != nil && m.PersonaState != nil {
		return *m.PersonaState
	}
	return 0
}

func (m *CMsgClientChangeStatus) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *CMsgClientChangeStatus) GetIsAutoGeneratedName() bool {
	if m != nil && m.IsAutoGeneratedName != nil {
		return *m.IsAutoGeneratedName
	}
	return false
}

func (m *CMsgClientChangeStatus) GetHighPriority() bool {
	if m != nil && m.HighPriority != nil {
		return *m.HighPriority
	}
	return false
}

func (m *CMsgClientChangeStatus) GetPersonaSetByUser() bool {
	if m != nil && m.PersonaSetByUser != nil {
		return *m.PersonaSetByUser
	}
	return false
}
