// Code generated by protoc-gen-go.
// source: steammessages_clientserver.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CMsgClientHeartBeat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgClientHeartBeat) Reset()         { *m = CMsgClientHeartBeat{} }
func (m *CMsgClientHeartBeat) String() string { return proto.CompactTextString(m) }
func (*CMsgClientHeartBeat) ProtoMessage()    {}
